package net.momirealms.craftengine.bukkit.plugin.command.feature;

import net.kyori.adventure.text.Component;
import net.momirealms.craftengine.bukkit.plugin.command.BukkitCommandFeature;
import net.momirealms.craftengine.core.pack.Identifier;
import net.momirealms.craftengine.core.plugin.CraftEngine;
import net.momirealms.craftengine.core.plugin.command.CraftEngineCommandManager;
import net.momirealms.craftengine.core.plugin.locale.MessageConstants;
import net.momirealms.craftengine.core.util.FileUtils;
import org.bukkit.command.CommandSender;
import org.incendo.cloud.Command;
import org.incendo.cloud.CommandManager;
import org.incendo.cloud.parser.standard.StringParser;
import org.snakeyaml.engine.v2.api.Dump;
import org.snakeyaml.engine.v2.api.DumpSettings;
import org.snakeyaml.engine.v2.common.FlowStyle;
import org.snakeyaml.engine.v2.common.ScalarStyle;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

public final class CreateResourceCommand extends BukkitCommandFeature<CommandSender> {

    public CreateResourceCommand(CraftEngineCommandManager<CommandSender> commandManager, CraftEngine plugin) {
        super(commandManager, plugin);
    }

    @Override
    public Command.Builder<? extends CommandSender> assembleCommand(CommandManager<CommandSender> manager, Command.Builder<CommandSender> builder) {
        return builder
                .flag(manager.flagBuilder("silent").withAliases("s"))
                .flag(manager.flagBuilder("full").withAliases("f"))
                .required("pack", StringParser.stringComponent(StringParser.StringMode.SINGLE))
                .optional("namespace", StringParser.stringComponent(StringParser.StringMode.SINGLE))
                .optional("author", StringParser.stringComponent(StringParser.StringMode.SINGLE))
                .optional("description", StringParser.stringComponent(StringParser.StringMode.GREEDY_FLAG_YIELDING))
                .handler(context -> {
                    String packFolder = context.get("pack");
                    Path packPath = plugin().dataFolderPath().resolve("resources").resolve(packFolder);
                    if (Files.exists(packPath)) {
                        handleFeedback(context, MessageConstants.COMMAND_RESOURCE_CREATE_FAILURE_EXISTS, Component.text(packFolder));
                        return;
                    }
                    Path configurationPath = packPath.resolve("configuration");
                    Path resourcepackPath = packPath.resolve("resourcepack");
                    Path packMetaPath = packPath.resolve("pack.yml");
                    String namespace = context.getOrDefault("namespace", packFolder);
                    if (!Identifier.isValidNamespace(namespace)) {
                        handleFeedback(context, MessageConstants.COMMAND_RESOURCE_CREATE_FAILURE_INVALID_NAMESPACE, Component.text(packFolder), Component.text(namespace));
                        return;
                    }
                    String author = context.getOrDefault("author", "CraftEngine");
                    String description = context.getOrDefault("description", "Auto-generated by CraftEngine");
                    try {
                        FileUtils.createDirectoriesSafe(packPath);
                        FileUtils.createDirectoriesSafe(configurationPath);
                        Path namespacePath = resourcepackPath.resolve("assets").resolve(namespace);
                        FileUtils.createDirectoriesSafe(namespacePath);
                        Path modelsPath = namespacePath.resolve("models");
                        FileUtils.createDirectoriesSafe(modelsPath.resolve("block"));
                        FileUtils.createDirectoriesSafe(modelsPath.resolve("item"));
                        Path texturesPath = namespacePath.resolve("textures");
                        FileUtils.createDirectoriesSafe(texturesPath.resolve("block"));
                        FileUtils.createDirectoriesSafe(texturesPath.resolve("font"));
                        FileUtils.createDirectoriesSafe(texturesPath.resolve("gui").resolve("sprites").resolve("tooltip"));
                        FileUtils.createDirectoriesSafe(texturesPath.resolve("item"));
                        FileUtils.createDirectoriesSafe(namespacePath.resolve("sounds"));

                        DumpSettings dumpSettings = DumpSettings.builder()
                                .setDefaultFlowStyle(FlowStyle.BLOCK)
                                .setDefaultScalarStyle(ScalarStyle.PLAIN)
                                .setSplitLines(false)
                                .setIndent(2)
                                .setIndicatorIndent(2)
                                .build();
                        Map<String, Object> data = new LinkedHashMap<>();
                        data.put("author", author);
                        data.put("description", description);
                        data.put("version", "1.0");
                        data.put("namespace", namespace);
                        data.put("enable", true);
                        Dump dump = new Dump(dumpSettings);
                        String yamlOutput = dump.dumpToString(data);
                        Files.writeString(packMetaPath, yamlOutput);
                    } catch (IOException e) {
                        handleFeedback(context, MessageConstants.COMMAND_RESOURCE_CREATE_FAILURE_UNKNOWN, Component.text(packFolder), Component.text(e.getMessage()));
                        return;
                    }
                    handleFeedback(context, MessageConstants.COMMAND_RESOURCE_CREATE_SUCCESS, Component.text(packFolder));
                });
    }

    @Override
    public String getFeatureID() {
        return "create_resource";
    }
}
